version: 2.1

jobs:
  build:
    docker:
      - image: afbsre/pl-base:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: echo 'export DOCKER_BUILDKIT=0' >> "${BASH_ENV}"
      - run:
          name: docker compse up
          command: |
              cd /root/project
              docker compose up
              sleep 120
#          background: true
      - run: docker compose exec -T dblocal mysql -u root -p password adprism < dump.sql
