version: 2.1

jobs:
  build:
    docker:
      - image: afbsre/pl-base:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: echo 'export DOCKER_BUILDKIT=0' >> "${BASH_ENV}"
      - run:
          command: |
              cd /root/project
              docker compose up -d 
      - run:
          name: run without wait
          command: | 
              cd /root/project
              docker compose exec -T dblocal mysql -u root -ppassword -e "show tables FROM adprism;"
              docker compose exec -T dblocal mysql -u root -ppassword adprism < dump.sql
      - run:
          name: sleep 120s
          command: |
              cd /root/project
              sleep 120
              docker compose exec -T dblocal mysql -u root -ppassword -e "show tables FROM adprism;"
              docker compose exec -T dblocal mysql -u root -ppassword adprism < dump.sql
              docker compose exec -T dblocal mysql -u root -ppassword -e "show tables FROM adprism;"
          when: always
