version: 2.1

jobs:
  build:
    docker:
      - image: afbsre/pl-base:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: echo 'export DOCKER_BUILDKIT=0' >> "${BASH_ENV}"
      - run:
          command: |
              cd /root/project
              docker compose up
          background: true
      - run: | 
          cd /root/project
          sleep 120
          docker compose exec -T dblocal mysql -u root -p password adprism < dump.sql
